### ISSUE TITLE
Can't compile 

### ISSUE THREAD

**Issue by sigmowicz** [dmXq-development/android_kernel_samsung_sm8550-modules#1]
Hi, i used kernel (lineage-22.0), kernel modules (lineage-22.0-wifi), kernel devicetrees (lineage-22.0) from dmXq-development and i have this error even after update, here is the error. https://pastebin.com/nuSA0n41. I had the same issue on rising os android 15 (6.0) and bliss rom android 15. 

EDIT: Here is the right pastebin link https://pastebin.com/j70rBtRr

**Comment by guckesh** [comment]
lineage-22.0-wifi is for dm3q
